-npm ERR! Error: ENOENT, open '/home/jaesun/Git/space_log/client/package.json'
-npm ERR! If you need help, you may report this log at:
-npm ERR!     <http://github.com/isaacs/npm/issues>
-npm ERR! or email it to:
-npm ERR!     <npm-@googlegroups.com>
-
-npm ERR! System Linux 3.8.0-44-generic
-npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
-npm ERR! cwd /home/jaesun/Git/space_log/client
-npm ERR! node -v v0.10.22
-npm ERR! npm -v 1.3.14
-npm ERR! path /home/jaesun/Git/space_log/client/package.json
-npm ERR! code ENOENT
-npm ERR! errno 34
-npm ERR!
-npm ERR! Additional logging details can be found in:
-npm ERR!     /home/jaesun/Git/space_log/client/npm-debug.log
-npm ERR! not ok code 0
-start: missing job name
-Try `start --help' for more information.
-start: missing job name
-Try `start --help' for more information.
-start: missing job name
-Try `start --help' for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 224, in <module>
    test()
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 220, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/local/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
/usr/local/bin/python: No module named SimpleHTTpServer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 224, in <module>
    test()
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 220, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/local/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 224, in <module>
    test()
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 220, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/local/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 224, in <module>
    test()
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 220, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/local/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 224, in <module>
    test()
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 220, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/local/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 224, in <module>
    test()
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 220, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/local/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 224, in <module>
    test()
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 220, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/local/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 224, in <module>
    test()
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 220, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/local/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 224, in <module>
    test()
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 220, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/local/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
python: can't open file 'SimpleHTTPServer': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 224, in <module>
    test()
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 220, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/local/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
/usr/local/bin/python: No module named simpleHTTPServer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 224, in <module>
    test()
  File "/usr/local/lib/python2.7/SimpleHTTPServer.py", line 220, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/local/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
